---
meta:
  pipeline: concourse-tutorial-docker-compose

resources:
  - name: code
    type: git
    source:
      uri: https://github.com/drnic/concourse-tutorial-docker-compose

jobs:
  - name: integration
    plan:
      - aggregate:
        - get: code
          trigger: true
      - task: Run integration tests
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: netresearch/dcind
          inputs:
            - name: code
          run:
            path: sh
            args:
              - -ec
              - |
                source /docker-lib.sh
                start_docker

                # Run the container with tests and its dependencies.
                docker-compose -f code/ci/docker-compose.yml run tests

                # Cleanup.
                # Not sure if this is required.
                # It's quite possible that Concourse is smart enough to clean up the Docker mess itself.
                docker-compose -f code/ci/docker-compose.yml down
                docker volume rm $(docker volume ls -q)
