---
resources:
  - name: code
    type: git
    source:
      uri: https://github.com/drnic/concourse-tutorial-docker-compose

  - name: redis
    type: docker-image
    source:
      repository: redis
      tag: alpine

  - name: busybox
    type: docker-image
    source:
      repository: busybox

jobs:
  - name: integration
    plan:
      - aggregate:
        - get: code
          trigger: true
        - get: redis
          params: {save: true}
        - get: busybox
          params: {save: true}
      - task: Run integration tests
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: netresearch/dcind
          inputs:
            - name: code
            - name: redis
            - name: busybox
          run:
            path: sh
            args:
              - -ec
              - |
                source /docker-lib.sh
                start_docker

                # Run the container with tests and its dependencies.
                docker-compose -f ci/docker-compose.yml run tests

                # Cleanup.
                # Not sure if this is required.
                # It's quite possible that Concourse is smart enough to clean up the Docker mess itself.
                docker-compose -f ci/docker-compose.yml down
                docker volume rm $(docker volume ls -q)
